# Generated by Django 4.0.5 on 2022-06-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='image1',
            field=models.ImageField(null=True, upload_to='', verbose_name='Image 1'),
        ),
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.ImageField(null=True, upload_to='', verbose_name='Image 2'),
        ),
    ]
